# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container
COPY app/requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire app directory into the container
COPY app/ /app/

# Expose the port that the main app runs on
EXPOSE 8000

# Command to run the main app using Gunicorn
CMD ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:8000", "--config", "config/gunicorn_main.conf.py", "main:app"]
