services:
  main:
    build:
      context: .
      dockerfile: Dockerfile_main
    container_name: main_app
    ports:
      - "8000:8000"
    volumes:
      - ./instance:/instance
      - ./cache:/cache
      - ./logs:/logs
      - ./secrets:/secrets
    environment:
      - DOCKER_ENV=true
    depends_on:
      - scheduler

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile_scheduler
    container_name: scheduler_app
    volumes:
      - ./instance:/instance
      - ./cache:/cache
      - ./backups:/backups
      - ./logs:/logs
      - ./secrets:/secrets
    environment:
      - DOCKER_ENV=true

